env:
  commonjs: true
  es2021: true
  node: true
extends: standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
rules:
  "@typescript-eslint/no-unused-vars":
    - error
  "@typescript-eslint/consistent-type-definitions":
    - error
    - type